import { ElementProps, HonorableProps } from '../types'

import withHonorable from '../withHonorable'

export type ButtonBaseBaseProps = HonorableProps<ElementProps<'button'>>
export const ButtonBase = withHonorable<ButtonBaseBaseProps>('button', 'ButtonBase')
export type InputBaseBaseProps = HonorableProps<ElementProps<'input'>>
export const InputBase = withHonorable<InputBaseBaseProps>('input', 'InputBase')
export type MenuBaseBaseProps = HonorableProps<ElementProps<'menu'>>
export const MenuBase = withHonorable<MenuBaseBaseProps>('menu', 'MenuBase')
export type SelectBaseBaseProps = HonorableProps<ElementProps<'select'>>
export const SelectBase = withHonorable<SelectBaseBaseProps>('select', 'SelectBase')

export type AProps = HonorableProps<ElementProps<'a'>>
export const A = withHonorable<AProps>('a', 'A')
export type AbbrProps = HonorableProps<ElementProps<'abbr'>>
export const Abbr = withHonorable<AbbrProps>('abbr', 'Abbr')
export type AddressProps = HonorableProps<ElementProps<'address'>>
export const Address = withHonorable<AddressProps>('address', 'Address')
export type AreaProps = HonorableProps<ElementProps<'area'>>
export const Area = withHonorable<AreaProps>('area', 'Area')
export type ArticleProps = HonorableProps<ElementProps<'article'>>
export const Article = withHonorable<ArticleProps>('article', 'Article')
export type AsideProps = HonorableProps<ElementProps<'aside'>>
export const Aside = withHonorable<AsideProps>('aside', 'Aside')
export type AudioProps = HonorableProps<ElementProps<'audio'>>
export const Audio = withHonorable<AudioProps>('audio', 'Audio')
export type BProps = HonorableProps<ElementProps<'b'>>
export const B = withHonorable<BProps>('b', 'B')
export type BaseProps = HonorableProps<ElementProps<'base'>>
export const Base = withHonorable<BaseProps>('base', 'Base')
export type BdiProps = HonorableProps<ElementProps<'bdi'>>
export const Bdi = withHonorable<BdiProps>('bdi', 'Bdi')
export type BdoProps = HonorableProps<ElementProps<'bdo'>>
export const Bdo = withHonorable<BdoProps>('bdo', 'Bdo')
export type BlockquoteProps = HonorableProps<ElementProps<'blockquote'>>
export const Blockquote = withHonorable<BlockquoteProps>('blockquote', 'Blockquote')
export type BodyProps = HonorableProps<ElementProps<'body'>>
export const Body = withHonorable<BodyProps>('body', 'Body')
export type BrProps = HonorableProps<ElementProps<'br'>>
export const Br = withHonorable<BrProps>('br', 'Br')
export type CanvasProps = HonorableProps<ElementProps<'canvas'>>
export const Canvas = withHonorable<CanvasProps>('canvas', 'Canvas')
export type CaptionProps = HonorableProps<ElementProps<'caption'>>
export const Caption = withHonorable<CaptionProps>('caption', 'Caption')
export type CiteProps = HonorableProps<ElementProps<'cite'>>
export const Cite = withHonorable<CiteProps>('cite', 'Cite')
export type CodeProps = HonorableProps<ElementProps<'code'>>
export const Code = withHonorable<CodeProps>('code', 'Code')
export type ColProps = HonorableProps<ElementProps<'col'>>
export const Col = withHonorable<ColProps>('col', 'Col')
export type ColgroupProps = HonorableProps<ElementProps<'colgroup'>>
export const Colgroup = withHonorable<ColgroupProps>('colgroup', 'Colgroup')
export type DataProps = HonorableProps<ElementProps<'data'>>
export const Data = withHonorable<DataProps>('data', 'Data')
export type DatalistProps = HonorableProps<ElementProps<'datalist'>>
export const Datalist = withHonorable<DatalistProps>('datalist', 'Datalist')
export type DdProps = HonorableProps<ElementProps<'dd'>>
export const Dd = withHonorable<DdProps>('dd', 'Dd')
export type DelProps = HonorableProps<ElementProps<'del'>>
export const Del = withHonorable<DelProps>('del', 'Del')
export type DetailsProps = HonorableProps<ElementProps<'details'>>
export const Details = withHonorable<DetailsProps>('details', 'Details')
export type DfnProps = HonorableProps<ElementProps<'dfn'>>
export const Dfn = withHonorable<DfnProps>('dfn', 'Dfn')
export type DialogProps = HonorableProps<ElementProps<'dialog'>>
export const Dialog = withHonorable<DialogProps>('dialog', 'Dialog')
export type DivProps = HonorableProps<ElementProps<'div'>>
export const Div = withHonorable<DivProps>('div', 'Div')
export type DlProps = HonorableProps<ElementProps<'dl'>>
export const Dl = withHonorable<DlProps>('dl', 'Dl')
export type DtProps = HonorableProps<ElementProps<'dt'>>
export const Dt = withHonorable<DtProps>('dt', 'Dt')
export type EmProps = HonorableProps<ElementProps<'em'>>
export const Em = withHonorable<EmProps>('em', 'Em')
export type EmbedProps = HonorableProps<ElementProps<'embed'>>
export const Embed = withHonorable<EmbedProps>('embed', 'Embed')
export type FieldsetProps = HonorableProps<ElementProps<'fieldset'>>
export const Fieldset = withHonorable<FieldsetProps>('fieldset', 'Fieldset')
export type FigcaptionProps = HonorableProps<ElementProps<'figcaption'>>
export const Figcaption = withHonorable<FigcaptionProps>('figcaption', 'Figcaption')
export type FigureProps = HonorableProps<ElementProps<'figure'>>
export const Figure = withHonorable<FigureProps>('figure', 'Figure')
export type FooterProps = HonorableProps<ElementProps<'footer'>>
export const Footer = withHonorable<FooterProps>('footer', 'Footer')
export type FormProps = HonorableProps<ElementProps<'form'>>
export const Form = withHonorable<FormProps>('form', 'Form')
export type H1Props = HonorableProps<ElementProps<'h1'>>
export const H1 = withHonorable<H1Props>('h1', 'H1')
export type H2Props = HonorableProps<ElementProps<'h2'>>
export const H2 = withHonorable<H2Props>('h2', 'H2')
export type H3Props = HonorableProps<ElementProps<'h3'>>
export const H3 = withHonorable<H3Props>('h3', 'H3')
export type H4Props = HonorableProps<ElementProps<'h4'>>
export const H4 = withHonorable<H4Props>('h4', 'H4')
export type H5Props = HonorableProps<ElementProps<'h5'>>
export const H5 = withHonorable<H5Props>('h5', 'H5')
export type H6Props = HonorableProps<ElementProps<'h6'>>
export const H6 = withHonorable<H6Props>('h6', 'H6')
export type HeadProps = HonorableProps<ElementProps<'head'>>
export const Head = withHonorable<HeadProps>('head', 'Head')
export type HeaderProps = HonorableProps<ElementProps<'header'>>
export const Header = withHonorable<HeaderProps>('header', 'Header')
export type HrProps = HonorableProps<ElementProps<'hr'>>
export const Hr = withHonorable<HrProps>('hr', 'Hr')
// export type HtmlProps = HonorableProps<ElementProps<'html'>>
// export const Html = withHonorable<HtmlProps>('html', 'html') // Can't use this because it's a reserved word in the Theme
export type IProps = HonorableProps<ElementProps<'i'>>
export const I = withHonorable<IProps>('i', 'I')
export type IframeProps = HonorableProps<ElementProps<'iframe'>>
export const Iframe = withHonorable<IframeProps>('iframe', 'Iframe')
export type ImgProps = HonorableProps<ElementProps<'img'>>
export const Img = withHonorable<ImgProps>('img', 'Img')
export type InsProps = HonorableProps<ElementProps<'ins'>>
export const Ins = withHonorable<InsProps>('ins', 'Ins')
export type KbdProps = HonorableProps<ElementProps<'kbd'>>
export const Kbd = withHonorable<KbdProps>('kbd', 'Kbd')
export type LabelProps = HonorableProps<ElementProps<'label'>>
export const Label = withHonorable<LabelProps>('label', 'Label')
export type LegendProps = HonorableProps<ElementProps<'legend'>>
export const Legend = withHonorable<LegendProps>('legend', 'Legend')
export type LiProps = HonorableProps<ElementProps<'li'>>
export const Li = withHonorable<LiProps>('li', 'Li')
export type LinkProps = HonorableProps<ElementProps<'link'>>
export const Link = withHonorable<LinkProps>('link', 'Link')
export type MainProps = HonorableProps<ElementProps<'main'>>
export const Main = withHonorable<MainProps>('main', 'Main')
export type MapProps = HonorableProps<ElementProps<'map'>>
export const Map = withHonorable<MapProps>('map', 'Map')
export type MarkProps = HonorableProps<ElementProps<'mark'>>
export const Mark = withHonorable<MarkProps>('mark', 'Mark')
export type MetaProps = HonorableProps<ElementProps<'meta'>>
export const Meta = withHonorable<MetaProps>('meta', 'Meta')
export type MeterProps = HonorableProps<ElementProps<'meter'>>
export const Meter = withHonorable<MeterProps>('meter', 'Meter')
export type NavProps = HonorableProps<ElementProps<'nav'>>
export const Nav = withHonorable<NavProps>('nav', 'Nav')
export type NoscriptProps = HonorableProps<ElementProps<'noscript'>>
export const Noscript = withHonorable<NoscriptProps>('noscript', 'Noscript')
// export type ObjectProps = HonorableProps<ElementProps<'object'>>
// export const Object = withHonorable<ObjectProps>('object', 'object') // Can't use this because it's a reserved Word
export type OlProps = HonorableProps<ElementProps<'ol'>>
export const Ol = withHonorable<OlProps>('ol', 'Ol')
export type OptgroupProps = HonorableProps<ElementProps<'optgroup'>>
export const Optgroup = withHonorable<OptgroupProps>('optgroup', 'Optgroup')
export type OptionProps = HonorableProps<ElementProps<'option'>>
export const Option = withHonorable<OptionProps>('option', 'Option')
export type OutputProps = HonorableProps<ElementProps<'output'>>
export const Output = withHonorable<OutputProps>('output', 'Output')
export type PProps = HonorableProps<ElementProps<'p'>>
export const P = withHonorable<PProps>('p', 'P')
export type ParamProps = HonorableProps<ElementProps<'param'>>
export const Param = withHonorable<ParamProps>('param', 'Param')
export type PictureProps = HonorableProps<ElementProps<'picture'>>
export const Picture = withHonorable<PictureProps>('picture', 'Picture')
export type PortalProps = HonorableProps<ElementProps<'portal'>>
export const Portal = withHonorable<PortalProps>('portal', 'Portal')
export type PreProps = HonorableProps<ElementProps<'pre'>>
export const Pre = withHonorable<PreProps>('pre', 'Pre')
export type ProgressProps = HonorableProps<ElementProps<'progress'>>
export const Progress = withHonorable<ProgressProps>('progress', 'Progress')
export type QProps = HonorableProps<ElementProps<'q'>>
export const Q = withHonorable<QProps>('q', 'Q')
export type RpProps = HonorableProps<ElementProps<'rp'>>
export const Rp = withHonorable<RpProps>('rp', 'Rp')
export type RtProps = HonorableProps<ElementProps<'rt'>>
export const Rt = withHonorable<RtProps>('rt', 'Rt')
export type RubyProps = HonorableProps<ElementProps<'ruby'>>
export const Ruby = withHonorable<RubyProps>('ruby', 'Ruby')
export type SProps = HonorableProps<ElementProps<'s'>>
export const S = withHonorable<SProps>('s', 'S')
export type SampProps = HonorableProps<ElementProps<'samp'>>
export const Samp = withHonorable<SampProps>('samp', 'Samp')
export type ScriptProps = HonorableProps<ElementProps<'script'>>
export const Script = withHonorable<ScriptProps>('script', 'Script')
export type SectionProps = HonorableProps<ElementProps<'section'>>
export const Section = withHonorable<SectionProps>('section', 'Section')
export type SlotProps = HonorableProps<ElementProps<'slot'>>
export const Slot = withHonorable<SlotProps>('slot', 'Slot')
export type SmallProps = HonorableProps<ElementProps<'small'>>
export const Small = withHonorable<SmallProps>('small', 'Small')
export type SourceProps = HonorableProps<ElementProps<'source'>>
export const Source = withHonorable<SourceProps>('source', 'Source')
export type SpanProps = HonorableProps<ElementProps<'span'>>
export const Span = withHonorable<SpanProps>('span', 'Span')
export type StrongProps = HonorableProps<ElementProps<'strong'>>
export const Strong = withHonorable<StrongProps>('strong', 'Strong')
export type StyleProps = HonorableProps<ElementProps<'style'>>
export const Style = withHonorable<StyleProps>('style', 'Style')
export type SubProps = HonorableProps<ElementProps<'sub'>>
export const Sub = withHonorable<SubProps>('sub', 'Sub')
export type SummaryProps = HonorableProps<ElementProps<'summary'>>
export const Summary = withHonorable<SummaryProps>('summary', 'Summary')
export type SupProps = HonorableProps<ElementProps<'sup'>>
export const Sup = withHonorable<SupProps>('sup', 'Sup')
export type SvgProps = HonorableProps<ElementProps<'svg'>>
export const Svg = withHonorable<SvgProps>('svg', 'Svg')
export type TableProps = HonorableProps<ElementProps<'table'>>
export const Table = withHonorable<TableProps>('table', 'Table')
export type TbodyProps = HonorableProps<ElementProps<'tbody'>>
export const Tbody = withHonorable<TbodyProps>('tbody', 'Tbody')
export type TdProps = HonorableProps<ElementProps<'td'>>
export const Td = withHonorable<TdProps>('td', 'Td')
export type TemplateProps = HonorableProps<ElementProps<'template'>>
export const Template = withHonorable<TemplateProps>('template', 'Template')
export type TextareaProps = HonorableProps<ElementProps<'textarea'>>
export const Textarea = withHonorable<TextareaProps>('textarea', 'Textarea')
export type TfootProps = HonorableProps<ElementProps<'tfoot'>>
export const Tfoot = withHonorable<TfootProps>('tfoot', 'Tfoot')
export type ThProps = HonorableProps<ElementProps<'th'>>
export const Th = withHonorable<ThProps>('th', 'Th')
export type TheadProps = HonorableProps<ElementProps<'thead'>>
export const Thead = withHonorable<TheadProps>('thead', 'Thead')
export type TimeProps = HonorableProps<ElementProps<'time'>>
export const Time = withHonorable<TimeProps>('time', 'Time')
export type TitleProps = HonorableProps<ElementProps<'title'>>
export const Title = withHonorable<TitleProps>('title', 'Title')
export type TrProps = HonorableProps<ElementProps<'tr'>>
export const Tr = withHonorable<TrProps>('tr', 'Tr')
export type TrackProps = HonorableProps<ElementProps<'track'>>
export const Track = withHonorable<TrackProps>('track', 'Track')
export type UProps = HonorableProps<ElementProps<'u'>>
export const U = withHonorable<UProps>('u', 'U')
export type UlProps = HonorableProps<ElementProps<'ul'>>
export const Ul = withHonorable<UlProps>('ul', 'Ul')
export type VarProps = HonorableProps<ElementProps<'var'>>
export const Var = withHonorable<VarProps>('var', 'Var')
export type VideoProps = HonorableProps<ElementProps<'video'>>
export const Video = withHonorable<VideoProps>('video', 'Video')
export type WbrProps = HonorableProps<ElementProps<'wbr'>>
export const Wbr = withHonorable<WbrProps>('wbr', 'Wbr')
