import { ElementProps } from '../types'

import withHonorable from '../withHonorable'

export type ButtonBaseProps = ElementProps<'button'>
export const ButtonBase = withHonorable<ButtonBaseProps>('button', 'ButtonBase')
export type InputBaseProps = ElementProps<'input'>
export const InputBase = withHonorable<InputBaseProps>('input', 'InputBase')
export type MenuBaseProps = ElementProps<'menu'>
export const MenuBase = withHonorable<MenuBaseProps>('menu', 'MenuBase')
export type SelectBaseProps = ElementProps<'select'>
export const SelectBase = withHonorable<SelectBaseProps>('select', 'SelectBase')

export type AProps = ElementProps<'a'>
export const A = withHonorable<AProps>('a', 'A')
export type AbbrProps = ElementProps<'abbr'>
export const Abbr = withHonorable<AbbrProps>('abbr', 'Abbr')
export type AddressProps = ElementProps<'address'>
export const Address = withHonorable<AddressProps>('address', 'Address')
export type AreaProps = ElementProps<'area'>
export const Area = withHonorable<AreaProps>('area', 'Area')
export type ArticleProps = ElementProps<'article'>
export const Article = withHonorable<ArticleProps>('article', 'Article')
export type AsideProps = ElementProps<'aside'>
export const Aside = withHonorable<AsideProps>('aside', 'Aside')
export type AudioProps = ElementProps<'audio'>
export const Audio = withHonorable<AudioProps>('audio', 'Audio')
export type BProps = ElementProps<'b'>
export const B = withHonorable<BProps>('b', 'B')
export type BaseProps = ElementProps<'base'>
export const Base = withHonorable<BaseProps>('base', 'Base')
export type BdiProps = ElementProps<'bdi'>
export const Bdi = withHonorable<BdiProps>('bdi', 'Bdi')
export type BdoProps = ElementProps<'bdo'>
export const Bdo = withHonorable<BdoProps>('bdo', 'Bdo')
export type BlockquoteProps = ElementProps<'blockquote'>
export const Blockquote = withHonorable<BlockquoteProps>('blockquote', 'Blockquote')
export type BodyProps = ElementProps<'body'>
export const Body = withHonorable<BodyProps>('body', 'Body')
export type BrProps = ElementProps<'br'>
export const Br = withHonorable<BrProps>('br', 'Br')
export type CanvasProps = ElementProps<'canvas'>
export const Canvas = withHonorable<CanvasProps>('canvas', 'Canvas')
export type CaptionProps = ElementProps<'caption'>
export const Caption = withHonorable<CaptionProps>('caption', 'Caption')
export type CiteProps = ElementProps<'cite'>
export const Cite = withHonorable<CiteProps>('cite', 'Cite')
export type CodeProps = ElementProps<'code'>
export const Code = withHonorable<CodeProps>('code', 'Code')
export type ColProps = ElementProps<'col'>
export const Col = withHonorable<ColProps>('col', 'Col')
export type ColgroupProps = ElementProps<'colgroup'>
export const Colgroup = withHonorable<ColgroupProps>('colgroup', 'Colgroup')
export type DataProps = ElementProps<'data'>
export const Data = withHonorable<DataProps>('data', 'Data')
export type DatalistProps = ElementProps<'datalist'>
export const Datalist = withHonorable<DatalistProps>('datalist', 'Datalist')
export type DdProps = ElementProps<'dd'>
export const Dd = withHonorable<DdProps>('dd', 'Dd')
export type DelProps = ElementProps<'del'>
export const Del = withHonorable<DelProps>('del', 'Del')
export type DetailsProps = ElementProps<'details'>
export const Details = withHonorable<DetailsProps>('details', 'Details')
export type DfnProps = ElementProps<'dfn'>
export const Dfn = withHonorable<DfnProps>('dfn', 'Dfn')
export type DialogProps = ElementProps<'dialog'>
export const Dialog = withHonorable<DialogProps>('dialog', 'Dialog')
export type DivProps = ElementProps<'div'>
export const Div = withHonorable<DivProps>('div', 'Div')
export type DlProps = ElementProps<'dl'>
export const Dl = withHonorable<DlProps>('dl', 'Dl')
export type DtProps = ElementProps<'dt'>
export const Dt = withHonorable<DtProps>('dt', 'Dt')
export type EmProps = ElementProps<'em'>
export const Em = withHonorable<EmProps>('em', 'Em')
export type EmbedProps = ElementProps<'embed'>
export const Embed = withHonorable<EmbedProps>('embed', 'Embed')
export type FieldsetProps = ElementProps<'fieldset'>
export const Fieldset = withHonorable<FieldsetProps>('fieldset', 'Fieldset')
export type FigcaptionProps = ElementProps<'figcaption'>
export const Figcaption = withHonorable<FigcaptionProps>('figcaption', 'Figcaption')
export type FigureProps = ElementProps<'figure'>
export const Figure = withHonorable<FigureProps>('figure', 'Figure')
export type FooterProps = ElementProps<'footer'>
export const Footer = withHonorable<FooterProps>('footer', 'Footer')
export type FormProps = ElementProps<'form'>
export const Form = withHonorable<FormProps>('form', 'Form')
export type H1Props = ElementProps<'h1'>
export const H1 = withHonorable<H1Props>('h1', 'H1')
export type H2Props = ElementProps<'h2'>
export const H2 = withHonorable<H2Props>('h2', 'H2')
export type H3Props = ElementProps<'h3'>
export const H3 = withHonorable<H3Props>('h3', 'H3')
export type H4Props = ElementProps<'h4'>
export const H4 = withHonorable<H4Props>('h4', 'H4')
export type H5Props = ElementProps<'h5'>
export const H5 = withHonorable<H5Props>('h5', 'H5')
export type H6Props = ElementProps<'h6'>
export const H6 = withHonorable<H6Props>('h6', 'H6')
export type HeadProps = ElementProps<'head'>
export const Head = withHonorable<HeadProps>('head', 'Head')
export type HeaderProps = ElementProps<'header'>
export const Header = withHonorable<HeaderProps>('header', 'Header')
export type HrProps = ElementProps<'hr'>
export const Hr = withHonorable<HrProps>('hr', 'Hr')
// export type HtmlProps = ElementProps<'html'>
// export const Html = withHonorable<HtmlProps>('html', 'html') // Can't use this because it's a reserved word in the Theme
export type IProps = ElementProps<'i'>
export const I = withHonorable<IProps>('i', 'I')
export type IframeProps = ElementProps<'iframe'>
export const Iframe = withHonorable<IframeProps>('iframe', 'Iframe')
export type ImgProps = ElementProps<'img'>
export const Img = withHonorable<ImgProps>('img', 'Img')
export type InsProps = ElementProps<'ins'>
export const Ins = withHonorable<InsProps>('ins', 'Ins')
export type KbdProps = ElementProps<'kbd'>
export const Kbd = withHonorable<KbdProps>('kbd', 'Kbd')
export type LabelProps = ElementProps<'label'>
export const Label = withHonorable<LabelProps>('label', 'Label')
export type LegendProps = ElementProps<'legend'>
export const Legend = withHonorable<LegendProps>('legend', 'Legend')
export type LiProps = ElementProps<'li'>
export const Li = withHonorable<LiProps>('li', 'Li')
export type LinkProps = ElementProps<'link'>
export const Link = withHonorable<LinkProps>('link', 'Link')
export type MainProps = ElementProps<'main'>
export const Main = withHonorable<MainProps>('main', 'Main')
export type MapProps = ElementProps<'map'>
export const Map = withHonorable<MapProps>('map', 'Map')
export type MarkProps = ElementProps<'mark'>
export const Mark = withHonorable<MarkProps>('mark', 'Mark')
export type MetaProps = ElementProps<'meta'>
export const Meta = withHonorable<MetaProps>('meta', 'Meta')
export type MeterProps = ElementProps<'meter'>
export const Meter = withHonorable<MeterProps>('meter', 'Meter')
export type NavProps = ElementProps<'nav'>
export const Nav = withHonorable<NavProps>('nav', 'Nav')
export type NoscriptProps = ElementProps<'noscript'>
export const Noscript = withHonorable<NoscriptProps>('noscript', 'Noscript')
// export type ObjectProps = ElementProps<'object'>
// export const Object = withHonorable<ObjectProps>('object', 'object') // Can't use this because it's a reserved Word
export type OlProps = ElementProps<'ol'>
export const Ol = withHonorable<OlProps>('ol', 'Ol')
export type OptgroupProps = ElementProps<'optgroup'>
export const Optgroup = withHonorable<OptgroupProps>('optgroup', 'Optgroup')
export type OptionProps = ElementProps<'option'>
export const Option = withHonorable<OptionProps>('option', 'Option')
export type OutputProps = ElementProps<'output'>
export const Output = withHonorable<OutputProps>('output', 'Output')
export type PProps = ElementProps<'p'>
export const P = withHonorable<PProps>('p', 'P')
export type ParamProps = ElementProps<'param'>
export const Param = withHonorable<ParamProps>('param', 'Param')
export type PictureProps = ElementProps<'picture'>
export const Picture = withHonorable<PictureProps>('picture', 'Picture')
export type PortalProps = ElementProps<'portal'>
export const Portal = withHonorable<PortalProps>('portal', 'Portal')
export type PreProps = ElementProps<'pre'>
export const Pre = withHonorable<PreProps>('pre', 'Pre')
export type ProgressProps = ElementProps<'progress'>
export const Progress = withHonorable<ProgressProps>('progress', 'Progress')
export type QProps = ElementProps<'q'>
export const Q = withHonorable<QProps>('q', 'Q')
export type RpProps = ElementProps<'rp'>
export const Rp = withHonorable<RpProps>('rp', 'Rp')
export type RtProps = ElementProps<'rt'>
export const Rt = withHonorable<RtProps>('rt', 'Rt')
export type RubyProps = ElementProps<'ruby'>
export const Ruby = withHonorable<RubyProps>('ruby', 'Ruby')
export type SProps = ElementProps<'s'>
export const S = withHonorable<SProps>('s', 'S')
export type SampProps = ElementProps<'samp'>
export const Samp = withHonorable<SampProps>('samp', 'Samp')
export type ScriptProps = ElementProps<'script'>
export const Script = withHonorable<ScriptProps>('script', 'Script')
export type SectionProps = ElementProps<'section'>
export const Section = withHonorable<SectionProps>('section', 'Section')
export type SlotProps = ElementProps<'slot'>
export const Slot = withHonorable<SlotProps>('slot', 'Slot')
export type SmallProps = ElementProps<'small'>
export const Small = withHonorable<SmallProps>('small', 'Small')
export type SourceProps = ElementProps<'source'>
export const Source = withHonorable<SourceProps>('source', 'Source')
export type SpanProps = ElementProps<'span'>
export const Span = withHonorable<SpanProps>('span', 'Span')
export type StrongProps = ElementProps<'strong'>
export const Strong = withHonorable<StrongProps>('strong', 'Strong')
export type StyleProps = ElementProps<'style'>
export const Style = withHonorable<StyleProps>('style', 'Style')
export type SubProps = ElementProps<'sub'>
export const Sub = withHonorable<SubProps>('sub', 'Sub')
export type SummaryProps = ElementProps<'summary'>
export const Summary = withHonorable<SummaryProps>('summary', 'Summary')
export type SupProps = ElementProps<'sup'>
export const Sup = withHonorable<SupProps>('sup', 'Sup')
export type SvgProps = ElementProps<'svg'>
export const Svg = withHonorable<SvgProps>('svg', 'Svg')
export type TableProps = ElementProps<'table'>
export const Table = withHonorable<TableProps>('table', 'Table')
export type TbodyProps = ElementProps<'tbody'>
export const Tbody = withHonorable<TbodyProps>('tbody', 'Tbody')
export type TdProps = ElementProps<'td'>
export const Td = withHonorable<TdProps>('td', 'Td')
export type TemplateProps = ElementProps<'template'>
export const Template = withHonorable<TemplateProps>('template', 'Template')
export type TextareaProps = ElementProps<'textarea'>
export const Textarea = withHonorable<TextareaProps>('textarea', 'Textarea')
export type TfootProps = ElementProps<'tfoot'>
export const Tfoot = withHonorable<TfootProps>('tfoot', 'Tfoot')
export type ThProps = ElementProps<'th'>
export const Th = withHonorable<ThProps>('th', 'Th')
export type TheadProps = ElementProps<'thead'>
export const Thead = withHonorable<TheadProps>('thead', 'Thead')
export type TimeProps = ElementProps<'time'>
export const Time = withHonorable<TimeProps>('time', 'Time')
export type TitleProps = ElementProps<'title'>
export const Title = withHonorable<TitleProps>('title', 'Title')
export type TrProps = ElementProps<'tr'>
export const Tr = withHonorable<TrProps>('tr', 'Tr')
export type TrackProps = ElementProps<'track'>
export const Track = withHonorable<TrackProps>('track', 'Track')
export type UProps = ElementProps<'u'>
export const U = withHonorable<UProps>('u', 'U')
export type UlProps = ElementProps<'ul'>
export const Ul = withHonorable<UlProps>('ul', 'Ul')
export type VarProps = ElementProps<'var'>
export const Var = withHonorable<VarProps>('var', 'Var')
export type VideoProps = ElementProps<'video'>
export const Video = withHonorable<VideoProps>('video', 'Video')
export type WbrProps = ElementProps<'wbr'>
export const Wbr = withHonorable<WbrProps>('wbr', 'Wbr')
