import { ElementProps, HonorableProps } from '../types'

import withHonorableTag from '../withHonorableTag'

export type ButtonBaseBaseProps = HonorableProps<ElementProps<'button'>>
export const ButtonBase = withHonorableTag<ButtonBaseBaseProps>('button', 'ButtonBase')
export type InputBaseBaseProps = HonorableProps<ElementProps<'input'>>
export const InputBase = withHonorableTag<InputBaseBaseProps>('input', 'InputBase')
export type MenuBaseBaseProps = HonorableProps<ElementProps<'menu'>>
export const MenuBase = withHonorableTag<MenuBaseBaseProps>('menu', 'MenuBase')
export type SelectBaseBaseProps = HonorableProps<ElementProps<'select'>>
export const SelectBase = withHonorableTag<SelectBaseBaseProps>('select', 'SelectBase')

export type AProps = HonorableProps<ElementProps<'a'>>
export const A = withHonorableTag<AProps>('a', 'A')
export type AbbrProps = HonorableProps<ElementProps<'abbr'>>
export const Abbr = withHonorableTag<AbbrProps>('abbr', 'Abbr')
export type AddressProps = HonorableProps<ElementProps<'address'>>
export const Address = withHonorableTag<AddressProps>('address', 'Address')
export type AreaProps = HonorableProps<ElementProps<'area'>>
export const Area = withHonorableTag<AreaProps>('area', 'Area')
export type ArticleProps = HonorableProps<ElementProps<'article'>>
export const Article = withHonorableTag<ArticleProps>('article', 'Article')
export type AsideProps = HonorableProps<ElementProps<'aside'>>
export const Aside = withHonorableTag<AsideProps>('aside', 'Aside')
export type AudioProps = HonorableProps<ElementProps<'audio'>>
export const Audio = withHonorableTag<AudioProps>('audio', 'Audio')
export type BProps = HonorableProps<ElementProps<'b'>>
export const B = withHonorableTag<BProps>('b', 'B')
export type BaseProps = HonorableProps<ElementProps<'base'>>
export const Base = withHonorableTag<BaseProps>('base', 'Base')
export type BdiProps = HonorableProps<ElementProps<'bdi'>>
export const Bdi = withHonorableTag<BdiProps>('bdi', 'Bdi')
export type BdoProps = HonorableProps<ElementProps<'bdo'>>
export const Bdo = withHonorableTag<BdoProps>('bdo', 'Bdo')
export type BlockquoteProps = HonorableProps<ElementProps<'blockquote'>>
export const Blockquote = withHonorableTag<BlockquoteProps>('blockquote', 'Blockquote')
export type BodyProps = HonorableProps<ElementProps<'body'>>
export const Body = withHonorableTag<BodyProps>('body', 'Body')
export type BrProps = HonorableProps<ElementProps<'br'>>
export const Br = withHonorableTag<BrProps>('br', 'Br')
export type CanvasProps = HonorableProps<ElementProps<'canvas'>>
export const Canvas = withHonorableTag<CanvasProps>('canvas', 'Canvas')
export type CaptionProps = HonorableProps<ElementProps<'caption'>>
export const Caption = withHonorableTag<CaptionProps>('caption', 'Caption')
export type CiteProps = HonorableProps<ElementProps<'cite'>>
export const Cite = withHonorableTag<CiteProps>('cite', 'Cite')
export type CodeProps = HonorableProps<ElementProps<'code'>>
export const Code = withHonorableTag<CodeProps>('code', 'Code')
export type ColProps = HonorableProps<ElementProps<'col'>>
export const Col = withHonorableTag<ColProps>('col', 'Col')
export type ColgroupProps = HonorableProps<ElementProps<'colgroup'>>
export const Colgroup = withHonorableTag<ColgroupProps>('colgroup', 'Colgroup')
export type DataProps = HonorableProps<ElementProps<'data'>>
export const Data = withHonorableTag<DataProps>('data', 'Data')
export type DatalistProps = HonorableProps<ElementProps<'datalist'>>
export const Datalist = withHonorableTag<DatalistProps>('datalist', 'Datalist')
export type DdProps = HonorableProps<ElementProps<'dd'>>
export const Dd = withHonorableTag<DdProps>('dd', 'Dd')
export type DelProps = HonorableProps<ElementProps<'del'>>
export const Del = withHonorableTag<DelProps>('del', 'Del')
export type DetailsProps = HonorableProps<ElementProps<'details'>>
export const Details = withHonorableTag<DetailsProps>('details', 'Details')
export type DfnProps = HonorableProps<ElementProps<'dfn'>>
export const Dfn = withHonorableTag<DfnProps>('dfn', 'Dfn')
export type DialogProps = HonorableProps<ElementProps<'dialog'>>
export const Dialog = withHonorableTag<DialogProps>('dialog', 'Dialog')
export type DivProps = HonorableProps<ElementProps<'div'>>
export const Div = withHonorableTag<DivProps>('div', 'Div')
export type DlProps = HonorableProps<ElementProps<'dl'>>
export const Dl = withHonorableTag<DlProps>('dl', 'Dl')
export type DtProps = HonorableProps<ElementProps<'dt'>>
export const Dt = withHonorableTag<DtProps>('dt', 'Dt')
export type EmProps = HonorableProps<ElementProps<'em'>>
export const Em = withHonorableTag<EmProps>('em', 'Em')
export type EmbedProps = HonorableProps<ElementProps<'embed'>>
export const Embed = withHonorableTag<EmbedProps>('embed', 'Embed')
export type FieldsetProps = HonorableProps<ElementProps<'fieldset'>>
export const Fieldset = withHonorableTag<FieldsetProps>('fieldset', 'Fieldset')
export type FigcaptionProps = HonorableProps<ElementProps<'figcaption'>>
export const Figcaption = withHonorableTag<FigcaptionProps>('figcaption', 'Figcaption')
export type FigureProps = HonorableProps<ElementProps<'figure'>>
export const Figure = withHonorableTag<FigureProps>('figure', 'Figure')
export type FooterProps = HonorableProps<ElementProps<'footer'>>
export const Footer = withHonorableTag<FooterProps>('footer', 'Footer')
export type FormProps = HonorableProps<ElementProps<'form'>>
export const Form = withHonorableTag<FormProps>('form', 'Form')
export type H1Props = HonorableProps<ElementProps<'h1'>>
export const H1 = withHonorableTag<H1Props>('h1', 'H1')
export type H2Props = HonorableProps<ElementProps<'h2'>>
export const H2 = withHonorableTag<H2Props>('h2', 'H2')
export type H3Props = HonorableProps<ElementProps<'h3'>>
export const H3 = withHonorableTag<H3Props>('h3', 'H3')
export type H4Props = HonorableProps<ElementProps<'h4'>>
export const H4 = withHonorableTag<H4Props>('h4', 'H4')
export type H5Props = HonorableProps<ElementProps<'h5'>>
export const H5 = withHonorableTag<H5Props>('h5', 'H5')
export type H6Props = HonorableProps<ElementProps<'h6'>>
export const H6 = withHonorableTag<H6Props>('h6', 'H6')
export type HeadProps = HonorableProps<ElementProps<'head'>>
export const Head = withHonorableTag<HeadProps>('head', 'Head')
export type HeaderProps = HonorableProps<ElementProps<'header'>>
export const Header = withHonorableTag<HeaderProps>('header', 'Header')
export type HrProps = HonorableProps<ElementProps<'hr'>>
export const Hr = withHonorableTag<HrProps>('hr', 'Hr')
// export type HtmlProps = HonorableProps<ElementProps<'html'>>
// export const Html = withHonorableTag<HtmlProps>('html', 'html') // Can't use this because it's a reserved word in the Theme
export type IProps = HonorableProps<ElementProps<'i'>>
export const I = withHonorableTag<IProps>('i', 'I')
export type IframeProps = HonorableProps<ElementProps<'iframe'>>
export const Iframe = withHonorableTag<IframeProps>('iframe', 'Iframe')
export type ImgProps = HonorableProps<ElementProps<'img'>>
export const Img = withHonorableTag<ImgProps>('img', 'Img')
export type InsProps = HonorableProps<ElementProps<'ins'>>
export const Ins = withHonorableTag<InsProps>('ins', 'Ins')
export type KbdProps = HonorableProps<ElementProps<'kbd'>>
export const Kbd = withHonorableTag<KbdProps>('kbd', 'Kbd')
export type LabelProps = HonorableProps<ElementProps<'label'>>
export const Label = withHonorableTag<LabelProps>('label', 'Label')
export type LegendProps = HonorableProps<ElementProps<'legend'>>
export const Legend = withHonorableTag<LegendProps>('legend', 'Legend')
export type LiProps = HonorableProps<ElementProps<'li'>>
export const Li = withHonorableTag<LiProps>('li', 'Li')
export type LinkProps = HonorableProps<ElementProps<'link'>>
export const Link = withHonorableTag<LinkProps>('link', 'Link')
export type MainProps = HonorableProps<ElementProps<'main'>>
export const Main = withHonorableTag<MainProps>('main', 'Main')
export type MapProps = HonorableProps<ElementProps<'map'>>
export const Map = withHonorableTag<MapProps>('map', 'Map')
export type MarkProps = HonorableProps<ElementProps<'mark'>>
export const Mark = withHonorableTag<MarkProps>('mark', 'Mark')
export type MetaProps = HonorableProps<ElementProps<'meta'>>
export const Meta = withHonorableTag<MetaProps>('meta', 'Meta')
export type MeterProps = HonorableProps<ElementProps<'meter'>>
export const Meter = withHonorableTag<MeterProps>('meter', 'Meter')
export type NavProps = HonorableProps<ElementProps<'nav'>>
export const Nav = withHonorableTag<NavProps>('nav', 'Nav')
export type NoscriptProps = HonorableProps<ElementProps<'noscript'>>
export const Noscript = withHonorableTag<NoscriptProps>('noscript', 'Noscript')
// export type ObjectProps = HonorableProps<ElementProps<'object'>>
// export const Object = withHonorableTag<ObjectProps>('object', 'object') // Can't use this because it's a reserved Word
export type OlProps = HonorableProps<ElementProps<'ol'>>
export const Ol = withHonorableTag<OlProps>('ol', 'Ol')
export type OptgroupProps = HonorableProps<ElementProps<'optgroup'>>
export const Optgroup = withHonorableTag<OptgroupProps>('optgroup', 'Optgroup')
export type OptionProps = HonorableProps<ElementProps<'option'>>
export const Option = withHonorableTag<OptionProps>('option', 'Option')
export type OutputProps = HonorableProps<ElementProps<'output'>>
export const Output = withHonorableTag<OutputProps>('output', 'Output')
export type PProps = HonorableProps<ElementProps<'p'>>
export const P = withHonorableTag<PProps>('p', 'P')
export type ParamProps = HonorableProps<ElementProps<'param'>>
export const Param = withHonorableTag<ParamProps>('param', 'Param')
export type PictureProps = HonorableProps<ElementProps<'picture'>>
export const Picture = withHonorableTag<PictureProps>('picture', 'Picture')
export type PortalProps = HonorableProps<ElementProps<'portal'>>
export const Portal = withHonorableTag<PortalProps>('portal', 'Portal')
export type PreProps = HonorableProps<ElementProps<'pre'>>
export const Pre = withHonorableTag<PreProps>('pre', 'Pre')
export type ProgressProps = HonorableProps<ElementProps<'progress'>>
export const Progress = withHonorableTag<ProgressProps>('progress', 'Progress')
export type QProps = HonorableProps<ElementProps<'q'>>
export const Q = withHonorableTag<QProps>('q', 'Q')
export type RpProps = HonorableProps<ElementProps<'rp'>>
export const Rp = withHonorableTag<RpProps>('rp', 'Rp')
export type RtProps = HonorableProps<ElementProps<'rt'>>
export const Rt = withHonorableTag<RtProps>('rt', 'Rt')
export type RubyProps = HonorableProps<ElementProps<'ruby'>>
export const Ruby = withHonorableTag<RubyProps>('ruby', 'Ruby')
export type SProps = HonorableProps<ElementProps<'s'>>
export const S = withHonorableTag<SProps>('s', 'S')
export type SampProps = HonorableProps<ElementProps<'samp'>>
export const Samp = withHonorableTag<SampProps>('samp', 'Samp')
export type ScriptProps = HonorableProps<ElementProps<'script'>>
export const Script = withHonorableTag<ScriptProps>('script', 'Script')
export type SectionProps = HonorableProps<ElementProps<'section'>>
export const Section = withHonorableTag<SectionProps>('section', 'Section')
export type SlotProps = HonorableProps<ElementProps<'slot'>>
export const Slot = withHonorableTag<SlotProps>('slot', 'Slot')
export type SmallProps = HonorableProps<ElementProps<'small'>>
export const Small = withHonorableTag<SmallProps>('small', 'Small')
export type SourceProps = HonorableProps<ElementProps<'source'>>
export const Source = withHonorableTag<SourceProps>('source', 'Source')
export type SpanProps = HonorableProps<ElementProps<'span'>>
export const Span = withHonorableTag<SpanProps>('span', 'Span')
export type StrongProps = HonorableProps<ElementProps<'strong'>>
export const Strong = withHonorableTag<StrongProps>('strong', 'Strong')
export type StyleProps = HonorableProps<ElementProps<'style'>>
export const Style = withHonorableTag<StyleProps>('style', 'Style')
export type SubProps = HonorableProps<ElementProps<'sub'>>
export const Sub = withHonorableTag<SubProps>('sub', 'Sub')
export type SummaryProps = HonorableProps<ElementProps<'summary'>>
export const Summary = withHonorableTag<SummaryProps>('summary', 'Summary')
export type SupProps = HonorableProps<ElementProps<'sup'>>
export const Sup = withHonorableTag<SupProps>('sup', 'Sup')
export type SvgProps = HonorableProps<ElementProps<'svg'>>
export const Svg = withHonorableTag<SvgProps>('svg', 'Svg')
export type TableProps = HonorableProps<ElementProps<'table'>>
export const Table = withHonorableTag<TableProps>('table', 'Table')
export type TbodyProps = HonorableProps<ElementProps<'tbody'>>
export const Tbody = withHonorableTag<TbodyProps>('tbody', 'Tbody')
export type TdProps = HonorableProps<ElementProps<'td'>>
export const Td = withHonorableTag<TdProps>('td', 'Td')
export type TemplateProps = HonorableProps<ElementProps<'template'>>
export const Template = withHonorableTag<TemplateProps>('template', 'Template')
export type TextareaProps = HonorableProps<ElementProps<'textarea'>>
export const Textarea = withHonorableTag<TextareaProps>('textarea', 'Textarea')
export type TfootProps = HonorableProps<ElementProps<'tfoot'>>
export const Tfoot = withHonorableTag<TfootProps>('tfoot', 'Tfoot')
export type ThProps = HonorableProps<ElementProps<'th'>>
export const Th = withHonorableTag<ThProps>('th', 'Th')
export type TheadProps = HonorableProps<ElementProps<'thead'>>
export const Thead = withHonorableTag<TheadProps>('thead', 'Thead')
export type TimeProps = HonorableProps<ElementProps<'time'>>
export const Time = withHonorableTag<TimeProps>('time', 'Time')
export type TitleProps = HonorableProps<ElementProps<'title'>>
export const Title = withHonorableTag<TitleProps>('title', 'Title')
export type TrProps = HonorableProps<ElementProps<'tr'>>
export const Tr = withHonorableTag<TrProps>('tr', 'Tr')
export type TrackProps = HonorableProps<ElementProps<'track'>>
export const Track = withHonorableTag<TrackProps>('track', 'Track')
export type UProps = HonorableProps<ElementProps<'u'>>
export const U = withHonorableTag<UProps>('u', 'U')
export type UlProps = HonorableProps<ElementProps<'ul'>>
export const Ul = withHonorableTag<UlProps>('ul', 'Ul')
export type VarProps = HonorableProps<ElementProps<'var'>>
export const Var = withHonorableTag<VarProps>('var', 'Var')
export type VideoProps = HonorableProps<ElementProps<'video'>>
export const Video = withHonorableTag<VideoProps>('video', 'Video')
export type WbrProps = HonorableProps<ElementProps<'wbr'>>
export const Wbr = withHonorableTag<WbrProps>('wbr', 'Wbr')
